name: ybigta
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - iniconfig=2.3.0=py311hca03da5_0
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - packaging=25.0=py311hca03da5_1
  - pip=25.3=pyhc872135_0
  - pluggy=1.5.0=py311hca03da5_0
  - pygments=2.19.2=py311hca03da5_0
  - pytest=8.4.2=py311hca03da5_0
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - annotated-types==0.7.0
      - anyio==4.8.0
      - click==8.1.8
      - colorama==0.4.6
      - dnspython==2.7.0
      - email-validator==2.2.0
      - exceptiongroup==1.2.2
      - fastapi==0.115.6
      - h11==0.14.0
      - idna==3.10
      - mypy==1.14.1
      - mypy-extensions==1.0.0
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - sniffio==1.3.1
      - starlette==0.41.3
      - tomli==2.2.1
      - typing-extensions==4.12.2
      - uvicorn==0.34.0
prefix: /opt/homebrew/anaconda3/envs/ybigta
