name: ybigta
channels:
  - defaults
dependencies:
  - pygments=2.19.2=py311hca03da5_0
  - bzip2=1.0.8=h80987f9_6
  - xz=5.6.4=h80987f9_1
  - expat=2.7.3=h50f4ffc_4
  - ncurses=6.5=hee39554_0
  - libcxx=20.1.8=hd7fd590_1
  - zlib=1.3.1=h5f15de7_0
  - pluggy=1.5.0=py311hca03da5_0
  - pip=25.3=pyhc872135_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py311hca03da5_0
  - openssl=3.6.0
  - libexpat=2.7.3=h50f4ffc_4
  - readline=8.3=h0b18652_0
  - libzlib=1.3.1=h5f15de7_0
  - iniconfig=2.3.0=py311hca03da5_0
  - ca-certificates=2026.1.4
  - packaging=25.0=py311hca03da5_1
  - pytest=8.4.2=py311hca03da5_0
  - libffi=3.4.4=hca03da5_1
  - setuptools=80.9.0=py311hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - python=3.11.14=hf701271_0
  - selenium
  - webdriver-manager
  - pandas
  - pandas-stubs
  - beautifulsoup4
  - types-requests
prefix: /opt/homebrew/anaconda3/envs/ybigta
